services:
  frontend:
    container_name: travel-front
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - NUXT_PUBLIC_API_BASE_URL=${NUXT_PUBLIC_API_BASE_URL}
      - NUXT_PUBLIC_MEDIA_BASE_URL=${NUXT_PUBLIC_MEDIA_BASE_URL}
      - NUXT_API_BASE_URL=${NUXT_API_BASE_URL}
      - NITRO_HOST=0.0.0.0
      - NITRO_PORT=3000
    restart: unless-stopped
    networks:
      - travel-rt-network

networks:
  travel-rt-network:
    name: travel-rt-network
    driver: bridge
    external: true
