/* tslint:disable */
/* eslint-disable */
/**
 * Travel RT Parser API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface HTTPValidationError
 */
export interface HTTPValidationError {
    /**
     * 
     * @type {Array<ValidationError>}
     * @memberof HTTPValidationError
     */
    'detail'?: Array<ValidationError>;
}
/**
 * Ответ эндпоинта проверки здоровья сервиса.
 * @export
 * @interface HealthResponse
 */
export interface HealthResponse {
    /**
     * 
     * @type {string}
     * @memberof HealthResponse
     */
    'status': string;
}
/**
 * Ответ на действие модерации (approve/reject).
 * @export
 * @interface ModerationActionResult
 */
export interface ModerationActionResult {
    /**
     * 
     * @type {string}
     * @memberof ModerationActionResult
     */
    'status'?: ModerationActionResultStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof ModerationActionResult
     */
    'news_id': number;
    /**
     * 
     * @type {string}
     * @memberof ModerationActionResult
     */
    'moderation_status': string;
}

export const ModerationActionResultStatusEnum = {
    Ok: 'ok'
} as const;

export type ModerationActionResultStatusEnum = typeof ModerationActionResultStatusEnum[keyof typeof ModerationActionResultStatusEnum];

/**
 * Ответ на массовое одобрение новостей в статусе «на модерации».
 * @export
 * @interface ModerationApproveAllResult
 */
export interface ModerationApproveAllResult {
    /**
     * 
     * @type {string}
     * @memberof ModerationApproveAllResult
     */
    'status'?: ModerationApproveAllResultStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof ModerationApproveAllResult
     */
    'approved_count': number;
}

export const ModerationApproveAllResultStatusEnum = {
    Ok: 'ok'
} as const;

export type ModerationApproveAllResultStatusEnum = typeof ModerationApproveAllResultStatusEnum[keyof typeof ModerationApproveAllResultStatusEnum];

/**
 * Карточка новости для чтения (список и деталь).
 * @export
 * @interface NewsRead
 */
export interface NewsRead {
    /**
     * 
     * @type {number}
     * @memberof NewsRead
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof NewsRead
     */
    'external_id': string;
    /**
     * 
     * @type {string}
     * @memberof NewsRead
     */
    'external_source': string;
    /**
     * 
     * @type {string}
     * @memberof NewsRead
     */
    'external_url': string;
    /**
     * 
     * @type {string}
     * @memberof NewsRead
     */
    'parsed_title': string;
    /**
     * 
     * @type {string}
     * @memberof NewsRead
     */
    'parsed_description': string;
    /**
     * 
     * @type {string}
     * @memberof NewsRead
     */
    'parsed_created_at': string;
    /**
     * 
     * @type {string}
     * @memberof NewsRead
     */
    'parsed_topic': string;
    /**
     * 
     * @type {string}
     * @memberof NewsRead
     */
    'moderation_status': string;
    /**
     * 
     * @type {string}
     * @memberof NewsRead
     */
    'moderation_comment': string | null;
    /**
     * 
     * @type {boolean}
     * @memberof NewsRead
     */
    'is_sent_to_backend': boolean;
    /**
     * 
     * @type {number}
     * @memberof NewsRead
     */
    'backend_id': number | null;
    /**
     * 
     * @type {boolean}
     * @memberof NewsRead
     */
    'needs_backend_update': boolean;
}
/**
 * Тело запроса: пароль для входа.
 * @export
 * @interface TokenRequest
 */
export interface TokenRequest {
    /**
     * 
     * @type {string}
     * @memberof TokenRequest
     */
    'password': string;
}
/**
 * Ответ: access_token и тип.
 * @export
 * @interface TokenResponse
 */
export interface TokenResponse {
    /**
     * 
     * @type {string}
     * @memberof TokenResponse
     */
    'access_token': string;
    /**
     * 
     * @type {string}
     * @memberof TokenResponse
     */
    'token_type'?: string;
}
/**
 * 
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
    /**
     * 
     * @type {Array<ValidationErrorLocInner>}
     * @memberof ValidationError
     */
    'loc': Array<ValidationErrorLocInner>;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'msg': string;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'type': string;
}
/**
 * 
 * @export
 * @interface ValidationErrorLocInner
 */
export interface ValidationErrorLocInner {
}

/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Принимает пароль, возвращает JWT. Пароль задаётся в настройках (AUTH_PASSWORD).
         * @summary Login
         * @param {TokenRequest} tokenRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginApiModerationTokenPost: async (tokenRequest: TokenRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tokenRequest' is not null or undefined
            assertParamExists('loginApiModerationTokenPost', 'tokenRequest', tokenRequest)
            const localVarPath = `/api-moderation/token`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(tokenRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * Принимает пароль, возвращает JWT. Пароль задаётся в настройках (AUTH_PASSWORD).
         * @summary Login
         * @param {TokenRequest} tokenRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async loginApiModerationTokenPost(tokenRequest: TokenRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TokenResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.loginApiModerationTokenPost(tokenRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.loginApiModerationTokenPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * Принимает пароль, возвращает JWT. Пароль задаётся в настройках (AUTH_PASSWORD).
         * @summary Login
         * @param {AuthApiLoginApiModerationTokenPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginApiModerationTokenPost(requestParameters: AuthApiLoginApiModerationTokenPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<TokenResponse> {
            return localVarFp.loginApiModerationTokenPost(requestParameters.tokenRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - interface
 * @export
 * @interface AuthApi
 */
export interface AuthApiInterface {
    /**
     * Принимает пароль, возвращает JWT. Пароль задаётся в настройках (AUTH_PASSWORD).
     * @summary Login
     * @param {AuthApiLoginApiModerationTokenPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    loginApiModerationTokenPost(requestParameters: AuthApiLoginApiModerationTokenPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<TokenResponse>;

}

/**
 * Request parameters for loginApiModerationTokenPost operation in AuthApi.
 * @export
 * @interface AuthApiLoginApiModerationTokenPostRequest
 */
export interface AuthApiLoginApiModerationTokenPostRequest {
    /**
     * 
     * @type {TokenRequest}
     * @memberof AuthApiLoginApiModerationTokenPost
     */
    readonly tokenRequest: TokenRequest
}

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI implements AuthApiInterface {
    /**
     * Принимает пароль, возвращает JWT. Пароль задаётся в настройках (AUTH_PASSWORD).
     * @summary Login
     * @param {AuthApiLoginApiModerationTokenPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public loginApiModerationTokenPost(requestParameters: AuthApiLoginApiModerationTokenPostRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).loginApiModerationTokenPost(requestParameters.tokenRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ModerationApi - axios parameter creator
 * @export
 */
export const ModerationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Одобрить все новости со статусом «на модерации» (одним запросом к БД).
         * @summary Approve All Pending News
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        approveAllPendingNewsApiModerationModerationNewsApproveAllPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api-moderation/moderation/news/approve-all`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Одобрить все новости со статусом «на модерации» (одним запросом к БД).
         * @summary Approve All Pending News
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        approveAllPendingNewsApiModerationModerationNewsApproveAllPost_1: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api-moderation/moderation/news/approve-all`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Approve News
         * @param {number} newsId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        approveNewsApiModerationModerationNewsNewsIdApprovePost: async (newsId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'newsId' is not null or undefined
            assertParamExists('approveNewsApiModerationModerationNewsNewsIdApprovePost', 'newsId', newsId)
            const localVarPath = `/api-moderation/moderation/news/{news_id}/approve`
                .replace(`{${"news_id"}}`, encodeURIComponent(String(newsId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Approve News
         * @param {number} newsId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        approveNewsApiModerationModerationNewsNewsIdApprovePost_2: async (newsId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'newsId' is not null or undefined
            assertParamExists('approveNewsApiModerationModerationNewsNewsIdApprovePost_2', 'newsId', newsId)
            const localVarPath = `/api-moderation/moderation/news/{news_id}/approve`
                .replace(`{${"news_id"}}`, encodeURIComponent(String(newsId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get News
         * @param {number} newsId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNewsApiModerationModerationNewsNewsIdGet: async (newsId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'newsId' is not null or undefined
            assertParamExists('getNewsApiModerationModerationNewsNewsIdGet', 'newsId', newsId)
            const localVarPath = `/api-moderation/moderation/news/{news_id}`
                .replace(`{${"news_id"}}`, encodeURIComponent(String(newsId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get News
         * @param {number} newsId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNewsApiModerationModerationNewsNewsIdGet_3: async (newsId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'newsId' is not null or undefined
            assertParamExists('getNewsApiModerationModerationNewsNewsIdGet_3', 'newsId', newsId)
            const localVarPath = `/api-moderation/moderation/news/{news_id}`
                .replace(`{${"news_id"}}`, encodeURIComponent(String(newsId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Healthcheck
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthcheckApiModerationHealthGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api-moderation/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List Pending News
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPendingNewsApiModerationModerationPendingNewsGet: async (limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api-moderation/moderation/pending/news`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List Pending News
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPendingNewsApiModerationModerationPendingNewsGet_4: async (limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api-moderation/moderation/pending/news`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Принимает пароль, возвращает JWT. Пароль задаётся в настройках (AUTH_PASSWORD).
         * @summary Login
         * @param {TokenRequest} tokenRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginApiModerationTokenPost: async (tokenRequest: TokenRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tokenRequest' is not null or undefined
            assertParamExists('loginApiModerationTokenPost', 'tokenRequest', tokenRequest)
            const localVarPath = `/api-moderation/token`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(tokenRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Reject News
         * @param {number} newsId 
         * @param {string | null} [reason] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rejectNewsApiModerationModerationNewsNewsIdRejectPost: async (newsId: number, reason?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'newsId' is not null or undefined
            assertParamExists('rejectNewsApiModerationModerationNewsNewsIdRejectPost', 'newsId', newsId)
            const localVarPath = `/api-moderation/moderation/news/{news_id}/reject`
                .replace(`{${"news_id"}}`, encodeURIComponent(String(newsId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (reason !== undefined) {
                localVarQueryParameter['reason'] = reason;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Reject News
         * @param {number} newsId 
         * @param {string | null} [reason] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rejectNewsApiModerationModerationNewsNewsIdRejectPost_5: async (newsId: number, reason?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'newsId' is not null or undefined
            assertParamExists('rejectNewsApiModerationModerationNewsNewsIdRejectPost_5', 'newsId', newsId)
            const localVarPath = `/api-moderation/moderation/news/{news_id}/reject`
                .replace(`{${"news_id"}}`, encodeURIComponent(String(newsId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (reason !== undefined) {
                localVarQueryParameter['reason'] = reason;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ModerationApi - functional programming interface
 * @export
 */
export const ModerationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ModerationApiAxiosParamCreator(configuration)
    return {
        /**
         * Одобрить все новости со статусом «на модерации» (одним запросом к БД).
         * @summary Approve All Pending News
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async approveAllPendingNewsApiModerationModerationNewsApproveAllPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ModerationApproveAllResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.approveAllPendingNewsApiModerationModerationNewsApproveAllPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModerationApi.approveAllPendingNewsApiModerationModerationNewsApproveAllPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Одобрить все новости со статусом «на модерации» (одним запросом к БД).
         * @summary Approve All Pending News
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async approveAllPendingNewsApiModerationModerationNewsApproveAllPost_1(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ModerationApproveAllResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.approveAllPendingNewsApiModerationModerationNewsApproveAllPost_1(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModerationApi.approveAllPendingNewsApiModerationModerationNewsApproveAllPost_1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Approve News
         * @param {number} newsId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async approveNewsApiModerationModerationNewsNewsIdApprovePost(newsId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ModerationActionResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.approveNewsApiModerationModerationNewsNewsIdApprovePost(newsId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModerationApi.approveNewsApiModerationModerationNewsNewsIdApprovePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Approve News
         * @param {number} newsId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async approveNewsApiModerationModerationNewsNewsIdApprovePost_2(newsId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ModerationActionResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.approveNewsApiModerationModerationNewsNewsIdApprovePost_2(newsId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModerationApi.approveNewsApiModerationModerationNewsNewsIdApprovePost_2']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get News
         * @param {number} newsId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getNewsApiModerationModerationNewsNewsIdGet(newsId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<NewsRead>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getNewsApiModerationModerationNewsNewsIdGet(newsId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModerationApi.getNewsApiModerationModerationNewsNewsIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get News
         * @param {number} newsId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getNewsApiModerationModerationNewsNewsIdGet_3(newsId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<NewsRead>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getNewsApiModerationModerationNewsNewsIdGet_3(newsId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModerationApi.getNewsApiModerationModerationNewsNewsIdGet_3']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Healthcheck
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthcheckApiModerationHealthGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HealthResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.healthcheckApiModerationHealthGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModerationApi.healthcheckApiModerationHealthGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List Pending News
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listPendingNewsApiModerationModerationPendingNewsGet(limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<NewsRead>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listPendingNewsApiModerationModerationPendingNewsGet(limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModerationApi.listPendingNewsApiModerationModerationPendingNewsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List Pending News
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listPendingNewsApiModerationModerationPendingNewsGet_4(limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<NewsRead>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listPendingNewsApiModerationModerationPendingNewsGet_4(limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModerationApi.listPendingNewsApiModerationModerationPendingNewsGet_4']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Принимает пароль, возвращает JWT. Пароль задаётся в настройках (AUTH_PASSWORD).
         * @summary Login
         * @param {TokenRequest} tokenRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async loginApiModerationTokenPost(tokenRequest: TokenRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TokenResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.loginApiModerationTokenPost(tokenRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModerationApi.loginApiModerationTokenPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Reject News
         * @param {number} newsId 
         * @param {string | null} [reason] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async rejectNewsApiModerationModerationNewsNewsIdRejectPost(newsId: number, reason?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ModerationActionResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.rejectNewsApiModerationModerationNewsNewsIdRejectPost(newsId, reason, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModerationApi.rejectNewsApiModerationModerationNewsNewsIdRejectPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Reject News
         * @param {number} newsId 
         * @param {string | null} [reason] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async rejectNewsApiModerationModerationNewsNewsIdRejectPost_5(newsId: number, reason?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ModerationActionResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.rejectNewsApiModerationModerationNewsNewsIdRejectPost_5(newsId, reason, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModerationApi.rejectNewsApiModerationModerationNewsNewsIdRejectPost_5']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ModerationApi - factory interface
 * @export
 */
export const ModerationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ModerationApiFp(configuration)
    return {
        /**
         * Одобрить все новости со статусом «на модерации» (одним запросом к БД).
         * @summary Approve All Pending News
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        approveAllPendingNewsApiModerationModerationNewsApproveAllPost(options?: RawAxiosRequestConfig): AxiosPromise<ModerationApproveAllResult> {
            return localVarFp.approveAllPendingNewsApiModerationModerationNewsApproveAllPost(options).then((request) => request(axios, basePath));
        },
        /**
         * Одобрить все новости со статусом «на модерации» (одним запросом к БД).
         * @summary Approve All Pending News
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        approveAllPendingNewsApiModerationModerationNewsApproveAllPost_1(options?: RawAxiosRequestConfig): AxiosPromise<ModerationApproveAllResult> {
            return localVarFp.approveAllPendingNewsApiModerationModerationNewsApproveAllPost_1(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Approve News
         * @param {ModerationApiApproveNewsApiModerationModerationNewsNewsIdApprovePostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        approveNewsApiModerationModerationNewsNewsIdApprovePost(requestParameters: ModerationApiApproveNewsApiModerationModerationNewsNewsIdApprovePostRequest, options?: RawAxiosRequestConfig): AxiosPromise<ModerationActionResult> {
            return localVarFp.approveNewsApiModerationModerationNewsNewsIdApprovePost(requestParameters.newsId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Approve News
         * @param {ModerationApiApproveNewsApiModerationModerationNewsNewsIdApprovePost0Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        approveNewsApiModerationModerationNewsNewsIdApprovePost_2(requestParameters: ModerationApiApproveNewsApiModerationModerationNewsNewsIdApprovePost0Request, options?: RawAxiosRequestConfig): AxiosPromise<ModerationActionResult> {
            return localVarFp.approveNewsApiModerationModerationNewsNewsIdApprovePost_2(requestParameters.newsId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get News
         * @param {ModerationApiGetNewsApiModerationModerationNewsNewsIdGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNewsApiModerationModerationNewsNewsIdGet(requestParameters: ModerationApiGetNewsApiModerationModerationNewsNewsIdGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<NewsRead> {
            return localVarFp.getNewsApiModerationModerationNewsNewsIdGet(requestParameters.newsId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get News
         * @param {ModerationApiGetNewsApiModerationModerationNewsNewsIdGet0Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNewsApiModerationModerationNewsNewsIdGet_3(requestParameters: ModerationApiGetNewsApiModerationModerationNewsNewsIdGet0Request, options?: RawAxiosRequestConfig): AxiosPromise<NewsRead> {
            return localVarFp.getNewsApiModerationModerationNewsNewsIdGet_3(requestParameters.newsId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Healthcheck
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthcheckApiModerationHealthGet(options?: RawAxiosRequestConfig): AxiosPromise<HealthResponse> {
            return localVarFp.healthcheckApiModerationHealthGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List Pending News
         * @param {ModerationApiListPendingNewsApiModerationModerationPendingNewsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPendingNewsApiModerationModerationPendingNewsGet(requestParameters: ModerationApiListPendingNewsApiModerationModerationPendingNewsGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Array<NewsRead>> {
            return localVarFp.listPendingNewsApiModerationModerationPendingNewsGet(requestParameters.limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List Pending News
         * @param {ModerationApiListPendingNewsApiModerationModerationPendingNewsGet0Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPendingNewsApiModerationModerationPendingNewsGet_4(requestParameters: ModerationApiListPendingNewsApiModerationModerationPendingNewsGet0Request = {}, options?: RawAxiosRequestConfig): AxiosPromise<Array<NewsRead>> {
            return localVarFp.listPendingNewsApiModerationModerationPendingNewsGet_4(requestParameters.limit, options).then((request) => request(axios, basePath));
        },
        /**
         * Принимает пароль, возвращает JWT. Пароль задаётся в настройках (AUTH_PASSWORD).
         * @summary Login
         * @param {ModerationApiLoginApiModerationTokenPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginApiModerationTokenPost(requestParameters: ModerationApiLoginApiModerationTokenPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<TokenResponse> {
            return localVarFp.loginApiModerationTokenPost(requestParameters.tokenRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Reject News
         * @param {ModerationApiRejectNewsApiModerationModerationNewsNewsIdRejectPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rejectNewsApiModerationModerationNewsNewsIdRejectPost(requestParameters: ModerationApiRejectNewsApiModerationModerationNewsNewsIdRejectPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<ModerationActionResult> {
            return localVarFp.rejectNewsApiModerationModerationNewsNewsIdRejectPost(requestParameters.newsId, requestParameters.reason, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Reject News
         * @param {ModerationApiRejectNewsApiModerationModerationNewsNewsIdRejectPost0Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rejectNewsApiModerationModerationNewsNewsIdRejectPost_5(requestParameters: ModerationApiRejectNewsApiModerationModerationNewsNewsIdRejectPost0Request, options?: RawAxiosRequestConfig): AxiosPromise<ModerationActionResult> {
            return localVarFp.rejectNewsApiModerationModerationNewsNewsIdRejectPost_5(requestParameters.newsId, requestParameters.reason, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ModerationApi - interface
 * @export
 * @interface ModerationApi
 */
export interface ModerationApiInterface {
    /**
     * Одобрить все новости со статусом «на модерации» (одним запросом к БД).
     * @summary Approve All Pending News
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModerationApiInterface
     */
    approveAllPendingNewsApiModerationModerationNewsApproveAllPost(options?: RawAxiosRequestConfig): AxiosPromise<ModerationApproveAllResult>;

    /**
     * Одобрить все новости со статусом «на модерации» (одним запросом к БД).
     * @summary Approve All Pending News
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModerationApiInterface
     */
    approveAllPendingNewsApiModerationModerationNewsApproveAllPost_1(options?: RawAxiosRequestConfig): AxiosPromise<ModerationApproveAllResult>;

    /**
     * 
     * @summary Approve News
     * @param {ModerationApiApproveNewsApiModerationModerationNewsNewsIdApprovePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModerationApiInterface
     */
    approveNewsApiModerationModerationNewsNewsIdApprovePost(requestParameters: ModerationApiApproveNewsApiModerationModerationNewsNewsIdApprovePostRequest, options?: RawAxiosRequestConfig): AxiosPromise<ModerationActionResult>;

    /**
     * 
     * @summary Approve News
     * @param {ModerationApiApproveNewsApiModerationModerationNewsNewsIdApprovePost0Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModerationApiInterface
     */
    approveNewsApiModerationModerationNewsNewsIdApprovePost_2(requestParameters: ModerationApiApproveNewsApiModerationModerationNewsNewsIdApprovePost0Request, options?: RawAxiosRequestConfig): AxiosPromise<ModerationActionResult>;

    /**
     * 
     * @summary Get News
     * @param {ModerationApiGetNewsApiModerationModerationNewsNewsIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModerationApiInterface
     */
    getNewsApiModerationModerationNewsNewsIdGet(requestParameters: ModerationApiGetNewsApiModerationModerationNewsNewsIdGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<NewsRead>;

    /**
     * 
     * @summary Get News
     * @param {ModerationApiGetNewsApiModerationModerationNewsNewsIdGet0Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModerationApiInterface
     */
    getNewsApiModerationModerationNewsNewsIdGet_3(requestParameters: ModerationApiGetNewsApiModerationModerationNewsNewsIdGet0Request, options?: RawAxiosRequestConfig): AxiosPromise<NewsRead>;

    /**
     * 
     * @summary Healthcheck
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModerationApiInterface
     */
    healthcheckApiModerationHealthGet(options?: RawAxiosRequestConfig): AxiosPromise<HealthResponse>;

    /**
     * 
     * @summary List Pending News
     * @param {ModerationApiListPendingNewsApiModerationModerationPendingNewsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModerationApiInterface
     */
    listPendingNewsApiModerationModerationPendingNewsGet(requestParameters?: ModerationApiListPendingNewsApiModerationModerationPendingNewsGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<NewsRead>>;

    /**
     * 
     * @summary List Pending News
     * @param {ModerationApiListPendingNewsApiModerationModerationPendingNewsGet0Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModerationApiInterface
     */
    listPendingNewsApiModerationModerationPendingNewsGet_4(requestParameters?: ModerationApiListPendingNewsApiModerationModerationPendingNewsGet0Request, options?: RawAxiosRequestConfig): AxiosPromise<Array<NewsRead>>;

    /**
     * Принимает пароль, возвращает JWT. Пароль задаётся в настройках (AUTH_PASSWORD).
     * @summary Login
     * @param {ModerationApiLoginApiModerationTokenPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModerationApiInterface
     */
    loginApiModerationTokenPost(requestParameters: ModerationApiLoginApiModerationTokenPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<TokenResponse>;

    /**
     * 
     * @summary Reject News
     * @param {ModerationApiRejectNewsApiModerationModerationNewsNewsIdRejectPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModerationApiInterface
     */
    rejectNewsApiModerationModerationNewsNewsIdRejectPost(requestParameters: ModerationApiRejectNewsApiModerationModerationNewsNewsIdRejectPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<ModerationActionResult>;

    /**
     * 
     * @summary Reject News
     * @param {ModerationApiRejectNewsApiModerationModerationNewsNewsIdRejectPost0Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModerationApiInterface
     */
    rejectNewsApiModerationModerationNewsNewsIdRejectPost_5(requestParameters: ModerationApiRejectNewsApiModerationModerationNewsNewsIdRejectPost0Request, options?: RawAxiosRequestConfig): AxiosPromise<ModerationActionResult>;

}

/**
 * Request parameters for approveNewsApiModerationModerationNewsNewsIdApprovePost operation in ModerationApi.
 * @export
 * @interface ModerationApiApproveNewsApiModerationModerationNewsNewsIdApprovePostRequest
 */
export interface ModerationApiApproveNewsApiModerationModerationNewsNewsIdApprovePostRequest {
    /**
     * 
     * @type {number}
     * @memberof ModerationApiApproveNewsApiModerationModerationNewsNewsIdApprovePost
     */
    readonly newsId: number
}

/**
 * Request parameters for approveNewsApiModerationModerationNewsNewsIdApprovePost_2 operation in ModerationApi.
 * @export
 * @interface ModerationApiApproveNewsApiModerationModerationNewsNewsIdApprovePost0Request
 */
export interface ModerationApiApproveNewsApiModerationModerationNewsNewsIdApprovePost0Request {
    /**
     * 
     * @type {number}
     * @memberof ModerationApiApproveNewsApiModerationModerationNewsNewsIdApprovePost0
     */
    readonly newsId: number
}

/**
 * Request parameters for getNewsApiModerationModerationNewsNewsIdGet operation in ModerationApi.
 * @export
 * @interface ModerationApiGetNewsApiModerationModerationNewsNewsIdGetRequest
 */
export interface ModerationApiGetNewsApiModerationModerationNewsNewsIdGetRequest {
    /**
     * 
     * @type {number}
     * @memberof ModerationApiGetNewsApiModerationModerationNewsNewsIdGet
     */
    readonly newsId: number
}

/**
 * Request parameters for getNewsApiModerationModerationNewsNewsIdGet_3 operation in ModerationApi.
 * @export
 * @interface ModerationApiGetNewsApiModerationModerationNewsNewsIdGet0Request
 */
export interface ModerationApiGetNewsApiModerationModerationNewsNewsIdGet0Request {
    /**
     * 
     * @type {number}
     * @memberof ModerationApiGetNewsApiModerationModerationNewsNewsIdGet0
     */
    readonly newsId: number
}

/**
 * Request parameters for listPendingNewsApiModerationModerationPendingNewsGet operation in ModerationApi.
 * @export
 * @interface ModerationApiListPendingNewsApiModerationModerationPendingNewsGetRequest
 */
export interface ModerationApiListPendingNewsApiModerationModerationPendingNewsGetRequest {
    /**
     * 
     * @type {number}
     * @memberof ModerationApiListPendingNewsApiModerationModerationPendingNewsGet
     */
    readonly limit?: number
}

/**
 * Request parameters for listPendingNewsApiModerationModerationPendingNewsGet_4 operation in ModerationApi.
 * @export
 * @interface ModerationApiListPendingNewsApiModerationModerationPendingNewsGet0Request
 */
export interface ModerationApiListPendingNewsApiModerationModerationPendingNewsGet0Request {
    /**
     * 
     * @type {number}
     * @memberof ModerationApiListPendingNewsApiModerationModerationPendingNewsGet0
     */
    readonly limit?: number
}

/**
 * Request parameters for loginApiModerationTokenPost operation in ModerationApi.
 * @export
 * @interface ModerationApiLoginApiModerationTokenPostRequest
 */
export interface ModerationApiLoginApiModerationTokenPostRequest {
    /**
     * 
     * @type {TokenRequest}
     * @memberof ModerationApiLoginApiModerationTokenPost
     */
    readonly tokenRequest: TokenRequest
}

/**
 * Request parameters for rejectNewsApiModerationModerationNewsNewsIdRejectPost operation in ModerationApi.
 * @export
 * @interface ModerationApiRejectNewsApiModerationModerationNewsNewsIdRejectPostRequest
 */
export interface ModerationApiRejectNewsApiModerationModerationNewsNewsIdRejectPostRequest {
    /**
     * 
     * @type {number}
     * @memberof ModerationApiRejectNewsApiModerationModerationNewsNewsIdRejectPost
     */
    readonly newsId: number

    /**
     * 
     * @type {string}
     * @memberof ModerationApiRejectNewsApiModerationModerationNewsNewsIdRejectPost
     */
    readonly reason?: string | null
}

/**
 * Request parameters for rejectNewsApiModerationModerationNewsNewsIdRejectPost_5 operation in ModerationApi.
 * @export
 * @interface ModerationApiRejectNewsApiModerationModerationNewsNewsIdRejectPost0Request
 */
export interface ModerationApiRejectNewsApiModerationModerationNewsNewsIdRejectPost0Request {
    /**
     * 
     * @type {number}
     * @memberof ModerationApiRejectNewsApiModerationModerationNewsNewsIdRejectPost0
     */
    readonly newsId: number

    /**
     * 
     * @type {string}
     * @memberof ModerationApiRejectNewsApiModerationModerationNewsNewsIdRejectPost0
     */
    readonly reason?: string | null
}

/**
 * ModerationApi - object-oriented interface
 * @export
 * @class ModerationApi
 * @extends {BaseAPI}
 */
export class ModerationApi extends BaseAPI implements ModerationApiInterface {
    /**
     * Одобрить все новости со статусом «на модерации» (одним запросом к БД).
     * @summary Approve All Pending News
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModerationApi
     */
    public approveAllPendingNewsApiModerationModerationNewsApproveAllPost(options?: RawAxiosRequestConfig) {
        return ModerationApiFp(this.configuration).approveAllPendingNewsApiModerationModerationNewsApproveAllPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Одобрить все новости со статусом «на модерации» (одним запросом к БД).
     * @summary Approve All Pending News
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModerationApi
     */
    public approveAllPendingNewsApiModerationModerationNewsApproveAllPost_1(options?: RawAxiosRequestConfig) {
        return ModerationApiFp(this.configuration).approveAllPendingNewsApiModerationModerationNewsApproveAllPost_1(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Approve News
     * @param {ModerationApiApproveNewsApiModerationModerationNewsNewsIdApprovePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModerationApi
     */
    public approveNewsApiModerationModerationNewsNewsIdApprovePost(requestParameters: ModerationApiApproveNewsApiModerationModerationNewsNewsIdApprovePostRequest, options?: RawAxiosRequestConfig) {
        return ModerationApiFp(this.configuration).approveNewsApiModerationModerationNewsNewsIdApprovePost(requestParameters.newsId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Approve News
     * @param {ModerationApiApproveNewsApiModerationModerationNewsNewsIdApprovePost0Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModerationApi
     */
    public approveNewsApiModerationModerationNewsNewsIdApprovePost_2(requestParameters: ModerationApiApproveNewsApiModerationModerationNewsNewsIdApprovePost0Request, options?: RawAxiosRequestConfig) {
        return ModerationApiFp(this.configuration).approveNewsApiModerationModerationNewsNewsIdApprovePost_2(requestParameters.newsId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get News
     * @param {ModerationApiGetNewsApiModerationModerationNewsNewsIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModerationApi
     */
    public getNewsApiModerationModerationNewsNewsIdGet(requestParameters: ModerationApiGetNewsApiModerationModerationNewsNewsIdGetRequest, options?: RawAxiosRequestConfig) {
        return ModerationApiFp(this.configuration).getNewsApiModerationModerationNewsNewsIdGet(requestParameters.newsId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get News
     * @param {ModerationApiGetNewsApiModerationModerationNewsNewsIdGet0Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModerationApi
     */
    public getNewsApiModerationModerationNewsNewsIdGet_3(requestParameters: ModerationApiGetNewsApiModerationModerationNewsNewsIdGet0Request, options?: RawAxiosRequestConfig) {
        return ModerationApiFp(this.configuration).getNewsApiModerationModerationNewsNewsIdGet_3(requestParameters.newsId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Healthcheck
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModerationApi
     */
    public healthcheckApiModerationHealthGet(options?: RawAxiosRequestConfig) {
        return ModerationApiFp(this.configuration).healthcheckApiModerationHealthGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List Pending News
     * @param {ModerationApiListPendingNewsApiModerationModerationPendingNewsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModerationApi
     */
    public listPendingNewsApiModerationModerationPendingNewsGet(requestParameters: ModerationApiListPendingNewsApiModerationModerationPendingNewsGetRequest = {}, options?: RawAxiosRequestConfig) {
        return ModerationApiFp(this.configuration).listPendingNewsApiModerationModerationPendingNewsGet(requestParameters.limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List Pending News
     * @param {ModerationApiListPendingNewsApiModerationModerationPendingNewsGet0Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModerationApi
     */
    public listPendingNewsApiModerationModerationPendingNewsGet_4(requestParameters: ModerationApiListPendingNewsApiModerationModerationPendingNewsGet0Request = {}, options?: RawAxiosRequestConfig) {
        return ModerationApiFp(this.configuration).listPendingNewsApiModerationModerationPendingNewsGet_4(requestParameters.limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Принимает пароль, возвращает JWT. Пароль задаётся в настройках (AUTH_PASSWORD).
     * @summary Login
     * @param {ModerationApiLoginApiModerationTokenPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModerationApi
     */
    public loginApiModerationTokenPost(requestParameters: ModerationApiLoginApiModerationTokenPostRequest, options?: RawAxiosRequestConfig) {
        return ModerationApiFp(this.configuration).loginApiModerationTokenPost(requestParameters.tokenRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Reject News
     * @param {ModerationApiRejectNewsApiModerationModerationNewsNewsIdRejectPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModerationApi
     */
    public rejectNewsApiModerationModerationNewsNewsIdRejectPost(requestParameters: ModerationApiRejectNewsApiModerationModerationNewsNewsIdRejectPostRequest, options?: RawAxiosRequestConfig) {
        return ModerationApiFp(this.configuration).rejectNewsApiModerationModerationNewsNewsIdRejectPost(requestParameters.newsId, requestParameters.reason, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Reject News
     * @param {ModerationApiRejectNewsApiModerationModerationNewsNewsIdRejectPost0Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModerationApi
     */
    public rejectNewsApiModerationModerationNewsNewsIdRejectPost_5(requestParameters: ModerationApiRejectNewsApiModerationModerationNewsNewsIdRejectPost0Request, options?: RawAxiosRequestConfig) {
        return ModerationApiFp(this.configuration).rejectNewsApiModerationModerationNewsNewsIdRejectPost_5(requestParameters.newsId, requestParameters.reason, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * SystemApi - axios parameter creator
 * @export
 */
export const SystemApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Healthcheck
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthcheckApiModerationHealthGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api-moderation/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SystemApi - functional programming interface
 * @export
 */
export const SystemApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SystemApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Healthcheck
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthcheckApiModerationHealthGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HealthResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.healthcheckApiModerationHealthGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SystemApi.healthcheckApiModerationHealthGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SystemApi - factory interface
 * @export
 */
export const SystemApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SystemApiFp(configuration)
    return {
        /**
         * 
         * @summary Healthcheck
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthcheckApiModerationHealthGet(options?: RawAxiosRequestConfig): AxiosPromise<HealthResponse> {
            return localVarFp.healthcheckApiModerationHealthGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SystemApi - interface
 * @export
 * @interface SystemApi
 */
export interface SystemApiInterface {
    /**
     * 
     * @summary Healthcheck
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SystemApiInterface
     */
    healthcheckApiModerationHealthGet(options?: RawAxiosRequestConfig): AxiosPromise<HealthResponse>;

}

/**
 * SystemApi - object-oriented interface
 * @export
 * @class SystemApi
 * @extends {BaseAPI}
 */
export class SystemApi extends BaseAPI implements SystemApiInterface {
    /**
     * 
     * @summary Healthcheck
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SystemApi
     */
    public healthcheckApiModerationHealthGet(options?: RawAxiosRequestConfig) {
        return SystemApiFp(this.configuration).healthcheckApiModerationHealthGet(options).then((request) => request(this.axios, this.basePath));
    }
}



