/* tslint:disable */
/* eslint-disable */
/**
 * Travel RT Parser API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface HTTPValidationError
 */
export interface HTTPValidationError {
    /**
     * 
     * @type {Array<ValidationError>}
     * @memberof HTTPValidationError
     */
    'detail'?: Array<ValidationError>;
}
/**
 * Ответ эндпоинта проверки здоровья сервиса.
 * @export
 * @interface HealthResponse
 */
export interface HealthResponse {
    /**
     * 
     * @type {string}
     * @memberof HealthResponse
     */
    'status': string;
}
/**
 * Ответ на действие модерации (approve/reject).
 * @export
 * @interface ModerationActionResult
 */
export interface ModerationActionResult {
    /**
     * 
     * @type {string}
     * @memberof ModerationActionResult
     */
    'status'?: ModerationActionResultStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof ModerationActionResult
     */
    'news_id': number;
    /**
     * 
     * @type {string}
     * @memberof ModerationActionResult
     */
    'moderation_status': string;
}

export const ModerationActionResultStatusEnum = {
    Ok: 'ok'
} as const;

export type ModerationActionResultStatusEnum = typeof ModerationActionResultStatusEnum[keyof typeof ModerationActionResultStatusEnum];

/**
 * Карточка новости для чтения (список и деталь).
 * @export
 * @interface NewsRead
 */
export interface NewsRead {
    /**
     * 
     * @type {number}
     * @memberof NewsRead
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof NewsRead
     */
    'external_id': string;
    /**
     * 
     * @type {string}
     * @memberof NewsRead
     */
    'external_source': string;
    /**
     * 
     * @type {string}
     * @memberof NewsRead
     */
    'external_url': string;
    /**
     * 
     * @type {string}
     * @memberof NewsRead
     */
    'parsed_title': string;
    /**
     * 
     * @type {string}
     * @memberof NewsRead
     */
    'parsed_description': string;
    /**
     * 
     * @type {string}
     * @memberof NewsRead
     */
    'parsed_created_at': string;
    /**
     * 
     * @type {string}
     * @memberof NewsRead
     */
    'parsed_topic': string;
    /**
     * 
     * @type {string}
     * @memberof NewsRead
     */
    'moderation_status': string;
    /**
     * 
     * @type {string}
     * @memberof NewsRead
     */
    'moderation_comment': string | null;
    /**
     * 
     * @type {boolean}
     * @memberof NewsRead
     */
    'is_sent_to_backend': boolean;
    /**
     * 
     * @type {number}
     * @memberof NewsRead
     */
    'backend_id': number | null;
}
/**
 * Тело запроса: пароль для входа.
 * @export
 * @interface TokenRequest
 */
export interface TokenRequest {
    /**
     * 
     * @type {string}
     * @memberof TokenRequest
     */
    'password': string;
}
/**
 * Ответ: access_token и тип.
 * @export
 * @interface TokenResponse
 */
export interface TokenResponse {
    /**
     * 
     * @type {string}
     * @memberof TokenResponse
     */
    'access_token': string;
    /**
     * 
     * @type {string}
     * @memberof TokenResponse
     */
    'token_type'?: string;
}
/**
 * 
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
    /**
     * 
     * @type {Array<ValidationErrorLocInner>}
     * @memberof ValidationError
     */
    'loc': Array<ValidationErrorLocInner>;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'msg': string;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'type': string;
}
/**
 * 
 * @export
 * @interface ValidationErrorLocInner
 */
export interface ValidationErrorLocInner {
}

/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Принимает пароль, возвращает JWT. Пароль задаётся в настройках (AUTH_PASSWORD).
         * @summary Login
         * @param {TokenRequest} tokenRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginTokenPost: async (tokenRequest: TokenRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tokenRequest' is not null or undefined
            assertParamExists('loginTokenPost', 'tokenRequest', tokenRequest)
            const localVarPath = `/token`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(tokenRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * Принимает пароль, возвращает JWT. Пароль задаётся в настройках (AUTH_PASSWORD).
         * @summary Login
         * @param {TokenRequest} tokenRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async loginTokenPost(tokenRequest: TokenRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TokenResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.loginTokenPost(tokenRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.loginTokenPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * Принимает пароль, возвращает JWT. Пароль задаётся в настройках (AUTH_PASSWORD).
         * @summary Login
         * @param {AuthApiLoginTokenPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginTokenPost(requestParameters: AuthApiLoginTokenPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<TokenResponse> {
            return localVarFp.loginTokenPost(requestParameters.tokenRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - interface
 * @export
 * @interface AuthApi
 */
export interface AuthApiInterface {
    /**
     * Принимает пароль, возвращает JWT. Пароль задаётся в настройках (AUTH_PASSWORD).
     * @summary Login
     * @param {AuthApiLoginTokenPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    loginTokenPost(requestParameters: AuthApiLoginTokenPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<TokenResponse>;

}

/**
 * Request parameters for loginTokenPost operation in AuthApi.
 * @export
 * @interface AuthApiLoginTokenPostRequest
 */
export interface AuthApiLoginTokenPostRequest {
    /**
     * 
     * @type {TokenRequest}
     * @memberof AuthApiLoginTokenPost
     */
    readonly tokenRequest: TokenRequest
}

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI implements AuthApiInterface {
    /**
     * Принимает пароль, возвращает JWT. Пароль задаётся в настройках (AUTH_PASSWORD).
     * @summary Login
     * @param {AuthApiLoginTokenPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public loginTokenPost(requestParameters: AuthApiLoginTokenPostRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).loginTokenPost(requestParameters.tokenRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ModerationApi - axios parameter creator
 * @export
 */
export const ModerationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Approve News
         * @param {number} newsId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        approveNewsModerationNewsNewsIdApprovePost: async (newsId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'newsId' is not null or undefined
            assertParamExists('approveNewsModerationNewsNewsIdApprovePost', 'newsId', newsId)
            const localVarPath = `/moderation/news/{news_id}/approve`
                .replace(`{${"news_id"}}`, encodeURIComponent(String(newsId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get News
         * @param {number} newsId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNewsModerationNewsNewsIdGet: async (newsId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'newsId' is not null or undefined
            assertParamExists('getNewsModerationNewsNewsIdGet', 'newsId', newsId)
            const localVarPath = `/moderation/news/{news_id}`
                .replace(`{${"news_id"}}`, encodeURIComponent(String(newsId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List Pending News
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPendingNewsModerationPendingNewsGet: async (limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/moderation/pending/news`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Reject News
         * @param {number} newsId 
         * @param {string | null} [reason] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rejectNewsModerationNewsNewsIdRejectPost: async (newsId: number, reason?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'newsId' is not null or undefined
            assertParamExists('rejectNewsModerationNewsNewsIdRejectPost', 'newsId', newsId)
            const localVarPath = `/moderation/news/{news_id}/reject`
                .replace(`{${"news_id"}}`, encodeURIComponent(String(newsId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (reason !== undefined) {
                localVarQueryParameter['reason'] = reason;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ModerationApi - functional programming interface
 * @export
 */
export const ModerationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ModerationApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Approve News
         * @param {number} newsId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async approveNewsModerationNewsNewsIdApprovePost(newsId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ModerationActionResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.approveNewsModerationNewsNewsIdApprovePost(newsId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModerationApi.approveNewsModerationNewsNewsIdApprovePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get News
         * @param {number} newsId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getNewsModerationNewsNewsIdGet(newsId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<NewsRead>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getNewsModerationNewsNewsIdGet(newsId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModerationApi.getNewsModerationNewsNewsIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List Pending News
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listPendingNewsModerationPendingNewsGet(limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<NewsRead>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listPendingNewsModerationPendingNewsGet(limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModerationApi.listPendingNewsModerationPendingNewsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Reject News
         * @param {number} newsId 
         * @param {string | null} [reason] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async rejectNewsModerationNewsNewsIdRejectPost(newsId: number, reason?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ModerationActionResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.rejectNewsModerationNewsNewsIdRejectPost(newsId, reason, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModerationApi.rejectNewsModerationNewsNewsIdRejectPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ModerationApi - factory interface
 * @export
 */
export const ModerationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ModerationApiFp(configuration)
    return {
        /**
         * 
         * @summary Approve News
         * @param {ModerationApiApproveNewsModerationNewsNewsIdApprovePostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        approveNewsModerationNewsNewsIdApprovePost(requestParameters: ModerationApiApproveNewsModerationNewsNewsIdApprovePostRequest, options?: RawAxiosRequestConfig): AxiosPromise<ModerationActionResult> {
            return localVarFp.approveNewsModerationNewsNewsIdApprovePost(requestParameters.newsId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get News
         * @param {ModerationApiGetNewsModerationNewsNewsIdGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNewsModerationNewsNewsIdGet(requestParameters: ModerationApiGetNewsModerationNewsNewsIdGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<NewsRead> {
            return localVarFp.getNewsModerationNewsNewsIdGet(requestParameters.newsId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List Pending News
         * @param {ModerationApiListPendingNewsModerationPendingNewsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPendingNewsModerationPendingNewsGet(requestParameters: ModerationApiListPendingNewsModerationPendingNewsGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Array<NewsRead>> {
            return localVarFp.listPendingNewsModerationPendingNewsGet(requestParameters.limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Reject News
         * @param {ModerationApiRejectNewsModerationNewsNewsIdRejectPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rejectNewsModerationNewsNewsIdRejectPost(requestParameters: ModerationApiRejectNewsModerationNewsNewsIdRejectPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<ModerationActionResult> {
            return localVarFp.rejectNewsModerationNewsNewsIdRejectPost(requestParameters.newsId, requestParameters.reason, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ModerationApi - interface
 * @export
 * @interface ModerationApi
 */
export interface ModerationApiInterface {
    /**
     * 
     * @summary Approve News
     * @param {ModerationApiApproveNewsModerationNewsNewsIdApprovePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModerationApiInterface
     */
    approveNewsModerationNewsNewsIdApprovePost(requestParameters: ModerationApiApproveNewsModerationNewsNewsIdApprovePostRequest, options?: RawAxiosRequestConfig): AxiosPromise<ModerationActionResult>;

    /**
     * 
     * @summary Get News
     * @param {ModerationApiGetNewsModerationNewsNewsIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModerationApiInterface
     */
    getNewsModerationNewsNewsIdGet(requestParameters: ModerationApiGetNewsModerationNewsNewsIdGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<NewsRead>;

    /**
     * 
     * @summary List Pending News
     * @param {ModerationApiListPendingNewsModerationPendingNewsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModerationApiInterface
     */
    listPendingNewsModerationPendingNewsGet(requestParameters?: ModerationApiListPendingNewsModerationPendingNewsGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<NewsRead>>;

    /**
     * 
     * @summary Reject News
     * @param {ModerationApiRejectNewsModerationNewsNewsIdRejectPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModerationApiInterface
     */
    rejectNewsModerationNewsNewsIdRejectPost(requestParameters: ModerationApiRejectNewsModerationNewsNewsIdRejectPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<ModerationActionResult>;

}

/**
 * Request parameters for approveNewsModerationNewsNewsIdApprovePost operation in ModerationApi.
 * @export
 * @interface ModerationApiApproveNewsModerationNewsNewsIdApprovePostRequest
 */
export interface ModerationApiApproveNewsModerationNewsNewsIdApprovePostRequest {
    /**
     * 
     * @type {number}
     * @memberof ModerationApiApproveNewsModerationNewsNewsIdApprovePost
     */
    readonly newsId: number
}

/**
 * Request parameters for getNewsModerationNewsNewsIdGet operation in ModerationApi.
 * @export
 * @interface ModerationApiGetNewsModerationNewsNewsIdGetRequest
 */
export interface ModerationApiGetNewsModerationNewsNewsIdGetRequest {
    /**
     * 
     * @type {number}
     * @memberof ModerationApiGetNewsModerationNewsNewsIdGet
     */
    readonly newsId: number
}

/**
 * Request parameters for listPendingNewsModerationPendingNewsGet operation in ModerationApi.
 * @export
 * @interface ModerationApiListPendingNewsModerationPendingNewsGetRequest
 */
export interface ModerationApiListPendingNewsModerationPendingNewsGetRequest {
    /**
     * 
     * @type {number}
     * @memberof ModerationApiListPendingNewsModerationPendingNewsGet
     */
    readonly limit?: number
}

/**
 * Request parameters for rejectNewsModerationNewsNewsIdRejectPost operation in ModerationApi.
 * @export
 * @interface ModerationApiRejectNewsModerationNewsNewsIdRejectPostRequest
 */
export interface ModerationApiRejectNewsModerationNewsNewsIdRejectPostRequest {
    /**
     * 
     * @type {number}
     * @memberof ModerationApiRejectNewsModerationNewsNewsIdRejectPost
     */
    readonly newsId: number

    /**
     * 
     * @type {string}
     * @memberof ModerationApiRejectNewsModerationNewsNewsIdRejectPost
     */
    readonly reason?: string | null
}

/**
 * ModerationApi - object-oriented interface
 * @export
 * @class ModerationApi
 * @extends {BaseAPI}
 */
export class ModerationApi extends BaseAPI implements ModerationApiInterface {
    /**
     * 
     * @summary Approve News
     * @param {ModerationApiApproveNewsModerationNewsNewsIdApprovePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModerationApi
     */
    public approveNewsModerationNewsNewsIdApprovePost(requestParameters: ModerationApiApproveNewsModerationNewsNewsIdApprovePostRequest, options?: RawAxiosRequestConfig) {
        return ModerationApiFp(this.configuration).approveNewsModerationNewsNewsIdApprovePost(requestParameters.newsId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get News
     * @param {ModerationApiGetNewsModerationNewsNewsIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModerationApi
     */
    public getNewsModerationNewsNewsIdGet(requestParameters: ModerationApiGetNewsModerationNewsNewsIdGetRequest, options?: RawAxiosRequestConfig) {
        return ModerationApiFp(this.configuration).getNewsModerationNewsNewsIdGet(requestParameters.newsId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List Pending News
     * @param {ModerationApiListPendingNewsModerationPendingNewsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModerationApi
     */
    public listPendingNewsModerationPendingNewsGet(requestParameters: ModerationApiListPendingNewsModerationPendingNewsGetRequest = {}, options?: RawAxiosRequestConfig) {
        return ModerationApiFp(this.configuration).listPendingNewsModerationPendingNewsGet(requestParameters.limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Reject News
     * @param {ModerationApiRejectNewsModerationNewsNewsIdRejectPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModerationApi
     */
    public rejectNewsModerationNewsNewsIdRejectPost(requestParameters: ModerationApiRejectNewsModerationNewsNewsIdRejectPostRequest, options?: RawAxiosRequestConfig) {
        return ModerationApiFp(this.configuration).rejectNewsModerationNewsNewsIdRejectPost(requestParameters.newsId, requestParameters.reason, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * SystemApi - axios parameter creator
 * @export
 */
export const SystemApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Healthcheck
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthcheckHealthGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SystemApi - functional programming interface
 * @export
 */
export const SystemApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SystemApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Healthcheck
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthcheckHealthGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HealthResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.healthcheckHealthGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SystemApi.healthcheckHealthGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SystemApi - factory interface
 * @export
 */
export const SystemApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SystemApiFp(configuration)
    return {
        /**
         * 
         * @summary Healthcheck
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthcheckHealthGet(options?: RawAxiosRequestConfig): AxiosPromise<HealthResponse> {
            return localVarFp.healthcheckHealthGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SystemApi - interface
 * @export
 * @interface SystemApi
 */
export interface SystemApiInterface {
    /**
     * 
     * @summary Healthcheck
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SystemApiInterface
     */
    healthcheckHealthGet(options?: RawAxiosRequestConfig): AxiosPromise<HealthResponse>;

}

/**
 * SystemApi - object-oriented interface
 * @export
 * @class SystemApi
 * @extends {BaseAPI}
 */
export class SystemApi extends BaseAPI implements SystemApiInterface {
    /**
     * 
     * @summary Healthcheck
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SystemApi
     */
    public healthcheckHealthGet(options?: RawAxiosRequestConfig) {
        return SystemApiFp(this.configuration).healthcheckHealthGet(options).then((request) => request(this.axios, this.basePath));
    }
}



